### ISSUE TITLE
Table 'PROPERTIES' not found

### ISSUE THREAD

**Issue by skmatik** [jeremylong/dependency-check-gradle#108]
Hello, I tried your plugin, I followed the Quick start and I am getting the following error:

17:32:11.115 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.ConnectionFactory]
org.h2.jdbc.JdbcSQLException: Table "PROPERTIES" not found; SQL statement:
SELECT value FROM properties WHERE id = 'version' [42102-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.Parser.readTableOrView(Parser.java:5552)
        at org.h2.command.Parser.readTableFilter(Parser.java:1266)
        at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1946)
        at org.h2.command.Parser.parseSelectSimple(Parser.java:2095)
        at org.h2.command.Parser.parseSelectSub(Parser.java:1940)
        at org.h2.command.Parser.parseSelectUnion(Parser.java:1755)
        at org.h2.command.Parser.parseSelect(Parser.java:1743)
        at org.h2.command.Parser.parsePrepared(Parser.java:449)
        at org.h2.command.Parser.parse(Parser.java:321)
        at org.h2.command.Parser.parse(Parser.java:293)
        at org.h2.command.Parser.prepareCommand(Parser.java:258)
        at org.h2.engine.Session.prepareLocal(Session.java:578)
        at org.h2.engine.Session.prepareCommand(Session.java:519)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:7
3)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.ensureSchemaV
ersion(ConnectionFactory.java:420)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.initialize(Co
nnectionFactory.java:190)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection
(ConnectionFactory.java:231)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:226)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:196)
        at org.owasp.dependencycheck.Engine.openDatabase(Engine.java:950)
        at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:892)
        at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.j
ava:716)

A

**Comment by jeremylong** [comment]
Try running 

```
gradle dependencyCheckPurge
```

Then run `dependencyCheckAnalyze`.

If that doesn't work - can you provide any more information about your build and environment?

**Comment by skmatik** [comment]
I tried it again and now it seems working fine. Thanks.
