### ISSUE TITLE
Confusing "Unable to connect to the dependency-check database" on download issues

### ISSUE THREAD

**Issue by szpak** [jeremylong/dependency-check-gradle#123]
`./gradlew dependencyCheckUpdate` (for DC 4.0.2) for a full update fails with:

```
$ .gw dependencyCheckUpdate
Download Failed for NVD CVE - 2014
Some CVEs may not be reported.
Download Failed for NVD CVE - 2015
Some CVEs may not be reported.
Download Failed for NVD CVE - 2016
Some CVEs may not be reported.
> Task :dependencyCheckUpdate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyCheckUpdate'.
> Unable to connect to the dependency-check database
```
The error message is misleading (and `Some CVEs may not be reported.` suggests the error might not be critical).

It is required to use `-s` to get the root exception cause:
```
Caused by: org.owasp.dependencycheck.data.update.exception.UpdateException:
    The download was interrupted; unable to complete the update
```
or `--debug` to see that there are some 403 responses:
```
14:51:07.464 [WARN] [org.owasp.dependencycheck.data.update.nvd.DownloadTask] Download Failed for NVD CVE - 2018
Some CVEs may not be reported.
14:51:07.464 [INFO] [org.owasp.dependencycheck.data.update.nvd.DownloadTask] If you are behind a proxy you may need to configure dependency-check to use the proxy.
14:51:07.464 [DEBUG] [org.owasp.dependencycheck.data.update.nvd.DownloadTask] 
org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2018.xml.gz; unable to connect.
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:177)
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:93)
        at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:151)
        at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:43)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-2018.xml.gz; received response code 403.
        at org.owasp.dependencycheck.utils.Downloader.fetchFile(Downloader.java:158)
        ... 7 more
```

**Comment by jeremylong** [comment]
I adjusted the log level on some of the error messages - that should help with gradle.

**Comment by malejpavouk** [comment]
Additional issue is that MAX_DOWNLOAD_THREAD_POOL_SIZE does not seem to be respected. Which causes quota violation in NVD, when you have enough processors (leading to this error).
