### ISSUE TITLE
Unable to define RetireJS Configuration

### ISSUE THREAD

**Issue by bendudz** [jeremylong/dependency-check-gradle#130]
I have a project that I am attempting to prevent the retireJs analyser from executing against. I am using an internal NVD mirror & postgresql db. I am using 5.0.0-M3.1

This is my dependencyCheck config:
```
dependencyCheck {
    cve {
        urlModified = "my/internalurl"
        urlBase = "my/other/internalurl"
    }
    data {
        driver = "org.postgresql.Driver"
        connectionString = "jdbc:postgresql://mydb:5555/postgres"
        username = "dcuser"
        password = "myuserpass"
    }
    analyzers {
        retirejs {
            retireJsUrl = "my/internalurl/jsrepository.json"
        }
    }
}
```

I am executing the dependencyCheckUpdate task to initially populate my Postgresql db but getting an error:

> Failed to initialise the RetireJS repo

The stack trace points to the fact the dependencyChecker is unable to connect to the internet (in particular https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json)

Running the task with debug on I can see this getting called:
> org.owasp.dependencycheck.data.update.RetireJSDatasource _Begin RetireJS Update_

Followed by:
> org.owasp.dependencycheck.data.update.RetireJSDatasource _RetireJS Repo URL: https://raw.githubusercontent.com/Retirejs/retire.js/master/repository/jsrepository.json_

It would seem that the configuration for retireJs is not being honoured.  On my internet connected machine I can debug the task & see the plugin connecting to GitHub to grab the jsrepository.json file. This is the case even though I am overriding the config value.

Debug can be found here: [https://gist.github.com/bendudz/e29d656e979734ddae9ec6fd380b3572#file-depchecklog-L1084](url)

I also attempted to use the following configuration but this also appears to not stop retirejs from attempting to grab the repo file.
```
dependencyCheck {
    analyzers {
        retirejs {
            enabled = false
        }
    }
}
```

Has anyone else seen issues in this area or can reproduce my issue?

**Comment by msmsimondean** [comment]
Hi @bendudz I'm getting the same error.

**Comment by msmsimondean** [comment]
@bendudz I'm behind a corporate firewall and I think it's preventing the download of the RetireJS Gist file.  Are you also behind a corporate firewall that's doing the same thing?

**Comment by msmsimondean** [comment]
As @bendudz says, it would be good if disabling the RetireJS analyzer prevented the RetireJS files from being downloaded.

**Comment by bendudz** [comment]
> @bendudz I'm behind a corporate firewall and I think it's preventing the download of the RetireJS Gist file. Are you also behind a corporate firewall that's doing the same thing?

I am in an isolated environment. No access to GitHub from there. We host the repo file locally but the config doesn't seem to be respected by the Gradle plugin.

**Comment by msmsimondean** [comment]
@bendudz the Maven plugin seems to suffer from the same issue: https://github.com/jeremylong/DependencyCheck/issues/1467

**Comment by jeremylong** [comment]
I am unable to re-produce this bug.  The configuration below does prevent the downloading of the retireJS repository:

```groovy
dependencyCheck {
  analyzers {
    retirejs {
      enabled = false
    }
  }
}
```

The following configuration does correctly download the retireJS from a local mirror:

dependencyCheck {
  analyzers {
    retirejs {
      retireJsUrl = "https://internalurl/jsrepository.json"
    }
  }
}
```

If anyone is having this issue please provide the full debug log.

**Comment by bendudz** [comment]
Hi @jeremylong. Thanks for this great project & your reply to my issue.

I have run it again this morning with your recommended config. Unfortunately I'm still getting the same issue. I have written the debug log to a gist [here](https://gist.githubusercontent.com/bendudz/df75c42850fa4ad0f79a3d1b275273bb/raw/49bafe6330076a3f36665e40f43fe3c12fed0d08/DepCheckUpdate.log) 

I also removed the h2 database & jsrepository.json before doing so. After the update the odc & jsrepository.json are back. 

Just to confirm I'm running the dependencyCheckUpdate task with
```
dependencyCheck {
  analyzers {
    retirejs {
      enabled = false
    }
  }
}
```

I then again removed the jsrepository & odc files from the cache and run the task again. This time with:
```
dependencyCheck {
  analyzers {
    retirejs {
      retireJsUrl = "my/internalurl/jsrepository.json"
    }
  }
}
```

[Here](https://gist.githubusercontent.com/bendudz/48084fdf6949d6e5f6cb7ba2292d56a9/raw/962347b6cdc75eab70a5d548296c4339dd9cf102/DepCheckUpdate.log) is the debug log. Line 1496 shows the plugin grabbing the jsrepo file from the GitHub url.

**Comment by jeremylong** [comment]
@bendudz can you provide the debug log with the actual failure?  The logs posted above show it correctly pulling the data from github.  The logs do not show that anything has been configured for the `dependencyCheck` plugin.

**Comment by jeremylong** [comment]
If you are indicating that the last [log you posted](https://gist.githubusercontent.com/bendudz/48084fdf6949d6e5f6cb7ba2292d56a9/raw/962347b6cdc75eab70a5d548296c4339dd9cf102/DepCheckUpdate.log) was run with:

```groovy
dependencyCheck {
  analyzers {
    retirejs {
      retireJsUrl = "my/internalurl/jsrepository.json"
    }
  }
}
```

Then there is something else wrong in the build.gradle as the configuration is not being read.  Can you post the full build.gradle?  Is this a multi-project build?

**Comment by bendudz** [comment]
> If you are indicating that the last [log you posted](https://gist.githubusercontent.com/bendudz/48084fdf6949d6e5f6cb7ba2292d56a9/raw/962347b6cdc75eab70a5d548296c4339dd9cf102/DepCheckUpdate.log) was run with:
> 
> ```groovy
> dependencyCheck {
>   analyzers {
>     retirejs {
>       retireJsUrl = "my/internalurl/jsrepository.json"
>     }
>   }
> }
> ```
> 
> Then there is something else wrong in the build.gradle as the configuration is not being read. Can you post the full build.gradle? Is this a multi-project build?

Yes that was the config I used.


I'll try & grab the debug log in the morning. I've done a bit more digging on my local machine.

With this config:
```
dependencyCheck {
  analyzers {
    retirejs {
      retireJsUrl = "my/internalurl/jsrepository.json"
    }
  }
}
```

when I execute dependencyCheckUpdate, the retireJs configuration is not being read in at all. It still grabs the GitHub file.

Running dependencyCheckAnalyze reads the retireJs config successfully & I can see when I set an invalid url ("https://my/internalurl/jsrepository.json") a stack trace is raised - which is what I'd expect. Same build.gradle file, same retireJs config.

```
21:31:32.157 [DEBUG] [org.owasp.dependencycheck.data.update.RetireJSDataSource] RetireJS Repo URL: https://my/internalurl/jsrepository.json
21:31:32.349 [DEBUG] [org.owasp.dependencycheck.utils.H2DBLock] Lock released (Execution worker for ':') a9278ca5e4ac36ddaf3782280a82a445 @ 2019-06-03 21:31:32.349
21:31:32.349 [WARN] [org.owasp.dependencycheck.Engine] Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
21:31:32.349 [DEBUG] [org.owasp.dependencycheck.Engine] Update Error
org.owasp.dependencycheck.data.update.exception.UpdateException: Failed to initialize the RetireJS repo
	at org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:174)
	at org.owasp.dependencycheck.data.update.RetireJSDataSource.update(RetireJSDataSource.java:101)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:913)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:717)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:647)
	at org.owasp.dependencycheck.Engine$analyzeDependencies$2.call(Unknown Source)
	at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:701)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:668)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:337)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:326)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:311)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:75)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:158)
	at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:46)
	at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
	at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
	at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
	at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:49)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:42)
	at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:28)
	at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:136)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:60)
	at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:37)
	at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
	at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:95)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:88)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
	at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.ResolveIncrementalChangesTaskExecuter.execute(ResolveIncrementalChangesTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:46)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: my
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.owasp.dependencycheck.data.update.RetireJSDataSource.initializeRetireJsRepo(RetireJSDataSource.java:160)
	... 89 more
21:31:32.351 [DEBUG] [org.owasp.dependencycheck.Engine] 
```

When using 
```
dependencyCheck {
  analyzers {
    retirejs {
      enabled = false
    }
  }
}
```

and running dependencyCheckAnalyze, the log contains this line:
```
20:38:33.613 [DEBUG] [org.owasp.dependencycheck.utils.Settings] Setting: analyzer.retirejs.enabled='false'
```
which is what I'd expect.

It appears on the surface that the retireJs config is not read when using dependencyCheckUpdate, but it is when using dependencyCheckAnalyze.

**Comment by jeremylong** [comment]
The configuration handling was not centralized - so when I updated the `analyze` tasks to handle the retireJS URL I did not also add the configuration to the `update` task.  I have centralized the configuration initialization for ODC to avoid future issues like this.  The next release will be published soon with the bug fixed.

**Comment by bendudz** [comment]
Thanks @jeremylong
