### ISSUE TITLE
Unexpected Exception when running DependencyCheckAnalyze

### ISSUE THREAD

**Issue by reinouts** [jeremylong/dependency-check-gradle#156]
I'm trying to run dependencyCheckAnalyze but I'm getting an "Unexpected Exception" and no clue as to what might be wrong.

Details: https://scans.gradle.com/s/fv2g56gh3ksxa/

```
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during analysis:
        Unexpected Exception
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:705)
        at org.owasp.dependencycheck.Engine$analyzeDependencies$0.call(Unknown Source)
        at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:89)
        ... 91 more
```

[Gradle build file for reference](https://github.com/jeremylong/dependency-check-gradle/files/3755169/build.zip)

**Comment by reinouts** [comment]
I found https://github.com/jeremylong/DependencyCheck/issues/2079 and deleting the jsrepository.json file solved the issue. :+1:
