### ISSUE TITLE
No such property nonProxyHosts

### ISSUE THREAD

**Issue by patrickhousley** [jeremylong/dependency-check-gradle#185]
When migrating to configuring the proxy settings in `settings.gradle` I am getting the below error.

```
2020-03-27 10:56:46.545  Caused by: groovy.lang.MissingPropertyException: No such property: nonProxyHosts for class: org.gradle.internal.resource.transport.http.JavaSystemPropertiesHttpProxySettings
2020-03-27 10:56:46.545  	at org.owasp.dependencycheck.gradle.tasks.ConfiguredTask.configureProxy(ConfiguredTask.groovy:175)
2020-03-27 10:56:46.545  	at org.owasp.dependencycheck.gradle.tasks.ConfiguredTask.initializeSettings(ConfiguredTask.groovy:77)
2020-03-27 10:56:46.545  	at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:70)
```

System info:
```
10:05 $ ./gradlew -v

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_232 (Eclipse OpenJ9 openj9-0.17.0)
OS:           Linux 5.3.0-42-generic amd64
```

**Comment by jeremylong** [comment]
We just pushed 5.3.2.1 which should resolve this issue.
