### ISSUE TITLE
Error while trying to manually order tasks

### ISSUE THREAD

**Issue by vraravam** [jeremylong/dependency-check-gradle#2]
I'm trying to run the dependencyCheck task at the end of my build chain - so that I can get faster feedback on broken tests, etc. For this, I am using 
```
dependencyCheck.mustRunAfter jsTest
```
But, its failing with the following stack trace:
```
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method mustRunAfter() for arguments [task ':contractTest'] on org.owasp.dependencycheck.gradle.extension.CheckExtension_Decorated@6d0e45a5.
	at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
	at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:175)
	at org.owasp.dependencycheck.gradle.extension.CheckExtension_Decorated.invokeMethod(Unknown Source)
	at build_d3310nd5p6g1pudrt5tlgq4gx.run(/Users/vijay/dev/gruppoPam/store_assortment_service/build.gradle:204)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 50 more
```

**Comment by jeremylong** [comment]
Odd that this does not work.  I am not sure why, I'll likely need to post a question to the gradle forum. In the meantime a work around would be to do something like this:

```gradle
...
apply plugin: 'org.owasp.dependencycheck'

dependencyCheck {
	skipTestGroups=false
	outputDirectory=rootProject.file("test_artifacts/security-reports-${project.name}.html")
}



task hello(type: GreetingTask)

class GreetingTask extends DefaultTask {
    @TaskAction
    def greet() {
        println 'hello from GreetingTask'
    }
}

task runDependencyCheck <<{
    tasks.dependencyCheck.execute()
}
runDependencyCheck.mustRunAfter "hello"
...
