### ISSUE TITLE
Crash when generating report

### ISSUE THREAD

**Issue by imbeyondboredom** [jeremylong/dependency-check-gradle#20]
When running this plugin on an android project Im getting the error below. 

Command: ./gradlew dependencyCheck --info

Note that this error occurs only when putting the plugin on the app's build.gradle and not on the project level build.gradle. So from a project level standpoint it looks like this:
/build.gradle <-- when the dependency scanner is in this file it does not crash
/app/build.gradle <-- dependency scanner is in this file and has the crash

```
Parser Exception: templates/HtmlReport.vsl
org.apache.velocity.runtime.parser.ParseException: Encountered "[" at line 32, column 58144.
Was expecting one of:
    "," ...
    ")" ...
    <WHITESPACE> ...
    <DOT> ...
at org.apache.velocity.runtime.parser.Parser.generateParseException(Parser.java:3360)
    at org.apache.velocity.runtime.parser.Parser.jj_consume_token(Parser.java:3237)
    at org.apache.velocity.runtime.parser.Parser.Method(Parser.java:1207)
    at org.apache.velocity.runtime.parser.Parser.Reference(Parser.java:1247)
    at org.apache.velocity.runtime.parser.Parser.Statement(Parser.java:301)
    at org.apache.velocity.runtime.parser.Parser.process(Parser.java:258)
    at org.apache.velocity.runtime.parser.Parser.parse(Parser.java:105)
    at org.apache.velocity.runtime.RuntimeInstance.parse(RuntimeInstance.java:1042)
    at org.apache.velocity.runtime.RuntimeInstance.parse(RuntimeInstance.java:972)
    at org.apache.velocity.app.VelocityEngine.evaluate(VelocityEngine.java:307)
    at org.owasp.dependencycheck.reporting.ReportGenerator.generateReport(ReportGenerator.java:259)
```

**Comment by jeremylong** [comment]
Which version of the plugin is being used?

**Comment by imbeyondboredom** [comment]
1.4.3 but it also occurred when doing 1.4.1. Again this only seems to affect my machine though.

Note that I did download and am in the process of adding an analyzer with the core lib. While i didn't modify the HTMLReport.vsl it's possible it's different in master.. but that shouldn't affect this gradle plugin because it shouldn't point to my snapshot builds of that correct?
https://github.com/jeremylong/DependencyCheck

**Comment by jeremylong** [comment]
Double check the version number of the dependency-check-core you've been tinkering with - any chance it is set to 1.4.3?  

Clear your `~/.m2/repository/org/owasp` and then re-run dependency-check.  Does that fix the problem on your machine?

**Comment by sunian** [comment]
It seems the issue was that we were applying the plugin in the app `build.gradle`, but moving it to the root level `build.gradle` fixed it.

**Comment by jeremylong** [comment]
Still not entirely sure what was going on - but can this issue be closed now?

**Comment by imbeyondboredom** [comment]
No I think this is still an issue but poorly explained. Updated the title and description to match. I'll see if I can get an example project in case this is specific to our build.gradle file

**Comment by jeremylong** [comment]
@imbeyondboredom Any luck in creating a test case?

**Comment by imbeyondboredom** [comment]
I tried to recreate this in a slimmed down version but I can't. I'm going to close for now. If I find a way to re-create it then I'll re-open
