### ISSUE TITLE
Intermittent owasp dependencyCheck failure on Jenkins build job

### ISSUE THREAD

**Issue by motwanideepika-ee** [jeremylong/dependency-check-gradle#44]
Hi,

We are using the owasp dependencyCheck plugin in our project. 
Version used: 1.4.5.1
Gradle version used: 3.5

We are facing the following issue in our build jobs:
The build jobs fail intermittently saying " :dependencyCheck FAILED "

The stacktrace of the error is as follows: 
 

> :dependencyCheck
  Verifying dependencies for project stock-service
  Checking for updates and analyzing vulnerabilities for dependencies
  Unable to update Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
  Exception occurred initializing CPE Analyzer.
  Generating report for project stock-service
  Found 0 vulnerabilities in project stock-service
  :dependencyCheck FAILED
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
	org.xml.sax.SAXException: Unable to get primary key for new cpe: cpe:/a:uchida_yoko_co._ltd:assetbase:8.0
org.owasp.dependencycheck.data.nvdcve.DatabaseException: Unable to get primary key for new cpe: cpe:/a:uchida_yoko_co._ltd:assetbase:8.0
	An exception occurred accessing the database
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:543)
	at org.owasp.dependencycheck.Engine$analyzeDependencies$0.call(Unknown Source)
	at org.owasp.dependencycheck.gradle.tasks.Check.check(Check.groovy:86) 
	... 66 more

Could you help us with this?

**Comment by motwanideepika-ee** [comment]
A workaround for this issue is described in this link:

**https://github.com/jeremylong/DependencyCheck/issues/410**

This solution was not usable as is, we had to change the "autoUpdate=true" so that the service creates a db file if it does not already exist. After the above change ( i.e adding "data directory" configuration in dependencyCheck task [visit the above link for this config]), the issue seems to have been fixed.
