### ISSUE TITLE
DatabaseException: Unable to connect to the database

### ISSUE THREAD

**Issue by alinbutura** [jeremylong/dependency-check-gradle#46]
Hi everyone,

I am running the dependencyCheck task in debug mode with Gradle 3.5 and 
and I am getting the following error:
08:55:07.227 [DEBUG] [org.owasp.dependencycheck.data.nvdcve.ConnectionFactory]
org.h2.jdbc.JdbcSQLException: Feature not supported: "MV_STORE combined with FILE_LOCK=SERIALIZED" [50100-193]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.message.DbException.getUnsupportedException(DbException.java:216)
        at org.h2.engine.Database.<init>(Database.java:236)
        at org.h2.engine.Engine.openSession(Engine.java:64)
        at org.h2.engine.Engine.openSession(Engine.java:176)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
        at org.h2.engine.Engine.createSession(Engine.java:137)
        at org.h2.engine.Engine.createSession(Engine.java:27)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:115)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:99)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at org.owasp.dependencycheck.data.nvdcve.ConnectionFactory.getConnection(ConnectionFactory.java:228)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.open(CveDB.java:124)
        at org.owasp.dependencycheck.data.nvdcve.CveDB.<init>(CveDB.java:87)
        at org.owasp.dependencycheck.Engine.ensureDataExists(Engine.java:752)
        at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:501)
        at org.owasp.dependencycheck.Engine$analyzeDependencies$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.owasp.dependencycheck.gradle.tasks.Check.check(Check.groovy:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

It used to work just fine with previous dependency-check plugin versions. Can you advise?

Thank you,
Alin

**Comment by alinbutura** [comment]
Hi,

By configuring the plugin 'data' configuration it seems to work:
data {
   connectionString = 'jdbc:h2:file:%s;AUTOCOMMIT=ON;''
}
Is this introducing any regression? :-)
Thanks!

Kind regards,
Alin

**Comment by jeremylong** [comment]
The only possible issue with that configuration, using 1.4.5 or earlier, is
if you run multiple builds/dependency-check scans at the same time. The
issue arises when one of the builds is executing an update while the other
is analyzing - we've seen some random false negatives occur.

I'm hoping to release 2.0.0 this weekend (might be slightly delayed because
I have to update the gradle plugin to match the changes in the Maven
plugin). With 2.0.0 the issue described above has been fixed.

**Comment by baron1405** [comment]
I am using version 2.0.1 of the plugin with Gradle 4.0.1 on CentOS 7 and am getting the same error and stack trace as @alinbutura.

**Comment by jeremylong** [comment]
You should be able to get around the bug (for now) by specifying:

```gradle
data {
connectionString = 'jdbc:h2:file:%s;AUTOCOMMIT=ON;''
}
```

I'll do some more testing to try and get a solution working for both older and newer instances of gradle.

**Comment by stefanneuhaus** [comment]
I stumbled across the same error today when having added the current version of h2 as a buildscript dependency like this:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath('org.owasp:dependency-check-gradle:2.0.1')
        classpath 'com.h2database:h2:1.4.196'
    }
}
```

Due to this DependencyCheck will actually use the version 1.4.196, which seems not to work anymore with the pre-configured connection string.

**Comment by jeremylong** [comment]
@stefanneuhaus correct, I actually need to spend some time and see what version of H2 we can upgrade the core to (must be compiled against Java 7) and see if we can find a default connection string that will work with multiple JVMs connecting to it.

**Comment by baron1405** [comment]
... and for what it is worth, dropping down to only the AUTOCOMMIT flag worked for me in Gradle 4.0.1. Thanks Jeremy for working through this!

**Comment by jeremylong** [comment]
The next release of dependency-check will update the H2 database driver version. There are changes to the connections string - so if you have modified your connection string you will likely need to remove the modification for things to work smoothly when you upgrade. I'm hoping to push a release today/tomorrow.

**Comment by alinbutura** [comment]
Hi Jeremy,

Just to let you know: tried this morning the 2.0.0 version and it still exhibits the same behavior if I do not change the jdbc connection string. Could you let us know when the new version becomes available? Thanks a lot!

**Comment by jeremylong** [comment]
2.1.1 was released, see the [announcement here](https://groups.google.com/forum/#!topic/dependency-check/YZFHWB9I2qo). The fix for this issue was included.

Remember - if you changed your connection string and are using the embedded H2 database you should likely remove the change.

**Comment by ammy1999** [comment]
Hello,
when I add                     

> <connectionString>jdbc:h2:file:%s;FILE_LOCK=FS;AUTOCOMMIT=ON;</connectionString> 
in the configuration of dependency check in pom.xml , the error  database connection is resolved 
Can I unterstand the line added !!

**Comment by johnscancella** [comment]
I have been getting this since March 30.
```
gradle dependencyCheckUpdate --refresh-dependencies
Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml
Download https://plugins.gradle.org/m2/org/eclipse/jgit/org.eclipse.jgit.ui/maven-metadata.xml
Download https://plugins.gradle.org/m2/com/jcraft/jsch/maven-metadata.xml
Download https://plugins.gradle.org/m2/org/slf4j/slf4j-api/maven-metadata.xml
IO Exception: HEAD request returned a non-200 status code
IO Exception: HEAD request returned a non-200 status code
IO Exception: HEAD request returned a non-200 status code
IO Exception: HEAD request returned a non-200 status code

> Task :dependencyCheckUpdate FAILED
Unable to download the NVD CVE data; the results may not include the most recent CPE/CVEs from the NVD.

IO Exception: HEAD request returned a non-200 status code
IO Exception: HEAD request returned a non-200 status code

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencyCheckUpdate'.
> Unable to connect to the dependency-check database

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
1 actionable task: 1 executed
```

**Comment by bilal-fazlani** [comment]
I am facing the same issue. Is there a solution to this ?

**Comment by bilal-fazlani** [comment]
Is there any way to detect if the dependency-check database is up and running ?

**Comment by jeremylong** [comment]
Please upgrade to 3.1.2. The NVD changed some URLs; the upgrade should
resolve this issue.

**Comment by johnscancella** [comment]
@jeremylong that fixed it for me. Thanks for all the hard work figuring that out!

**Comment by gupta-the-god** [comment]
How do you upgrade the version?
