### ISSUE TITLE
CPE Analyzer issue - Lucene Codec

### ISSUE THREAD

**Issue by sivaswami** [jeremylong/dependency-check-gradle#77]
Hitting Below exception in 3.1.1. Seems Lucene is added to CPE analyzer. But I don't see lucene dependency added in build.gradle file.

```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.lucene.codecs.Codec$Holder
›   at org.apache.lucene.codecs.Codec.getDefault(Codec.java:140)
›   at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:120)
›   at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:140)
›   at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.buildIndex(CpeMemoryIndex.java:198)
›   at org.owasp.dependencycheck.data.cpe.CpeMemoryIndex.open(CpeMemoryIndex.java:124)
›   at org.owasp.dependencycheck.analyzer.CPEAnalyzer.open(CPEAnalyzer.java:181)
›   at org.owasp.dependencycheck.analyzer.CPEAnalyzer.prepareAnalyzer(CPEAnalyzer.java:150)
›   at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.prepare(AbstractAnalyzer.java:107)
›   at org.owasp.dependencycheck.Engine.initializeAnalyzer(Engine.java:817)
›   at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:662)
›   at org.owasp.dependencycheck.Engine$analyzeDependencies$0.call(Unknown Source)
›   at org.owasp.dependencycheck.gradle.tasks.AbstractAnalyze.analyze(AbstractAnalyze.groovy:82)
›   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
›   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
›   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
›   at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by jeremylong** [comment]
Lucene is a transitive dependency of [dependency-check-core](https://github.com/jeremylong/DependencyCheck/blob/master/core/pom.xml#L171) - the engine that actually does the analysis.

I wonder in your case if you are running into some JAR version conflicts on the classpath. Any chance the build.gradle is available somewhere on github? Or can you replicate the problem with a sample build.gradle?
